title: Flow
description: >
        Surveyal of computer vision
baseurl: '/'
url: "http://open.spin.systems"
paginate:	4 # The number of posts to show per page on your homepage
name: "Louis Maddox"
twitter:
  - biochemistries
  - permutans
markdown: kramdown
permalink: none
kramdown:
  parse_block_html: true
gems:
  - jekyll-paginate
